### PR TITLE
Init

### PR DESCRIPTION
**Pull request by peeke**

### CODE REVIEW

**Comment by EECOLOR** [comment]
@peeke Did you mean to close this pull request?

**Comment by peeke** [comment]
@EECOLOR I did, because it had some oversights, but I also ment to re-open it, which I forgot!

**Review by EECOLOR — COMMENTED** [review]
From a naive perspective the `Themes` one seems to be not needed. I think you added this to provide an extra layer of safety.

As it stands now this library provides a minimal amount of machinery that barely crosses (in my mind) the threshold for something to be in a library. To make it more clearly cross this threshold I think we need to add a few things:

- A structure of a theme: which properties does a theme minimally have? Can we also define some optional properties of a theme?
- Typing, this allows users of `useTheme` to get code hinting when using themes

**Comment by peeke** [comment]
> From a naive perspective the `Themes` one seems to be not needed. I think you added this to provide an extra layer of safety.
> 
> As it stands now this library provides a minimal amount of machinery that barely crosses (in my mind) the threshold for something to be in a library. To make it more clearly cross this threshold I think we need to add a few things:
> 
> * A structure of a theme: which properties does a theme minimally have? Can we also define some optional properties of a theme?
> * Typing, this allows users of `useTheme` to get code hinting when using themes

I started out with more code, but refactoring brought it down to this, which might now be closer to convention than library. We have a colorScheme discussion in the devsign meeting today, which might provide some input for minimum properties as well. 

Besides colors, I'm also perfectly okay with other properties (for instance font) to be part of a theme as well. This might open the door to 'abuse' of themes, which is where typing will also be helpful. Maybe start with a minimum set and provide clear instructions to request new properties through a PR.

**Comment by EECOLOR** [comment]
> Maybe start with a minimum set and provide clear instructions to request new properties through a PR.

That's a great idea! It would allow us to motivate the properties.

**Comment by peeke** [comment]
Ingehaald door de praktijk :)

**Pull request closed without merging**
